{{- range $pipeline  := .Values.VectorPipeline }}
apiVersion: observability.kaasops.io/v1alpha1
kind: VectorPipeline
metadata:
  name: {{ $pipeline.name }} 
  namespace: {{ $pipeline.nanamespace }}
spec:
  sources: 
  {{  toYaml $pipeline.sources | nindent 6 }}
  transforms: 
  {{  toYaml $pipeline.transforms | nindent 6 }}
  sinks:
  {{  toYaml $pipeline.transforms | nindent 6 }} 
---
{{- end }}
