apiVersion: v1
entries:
  vector-operator:
  - apiVersion: v2
    appVersion: pre-v0.0.32
    created: "2023-11-18T15:47:26.183552+02:00"
    description: A Helm chart to install Vector Operator
    digest: 797d0f6ec5af5613133fe4a642093eb519b9e7d77c43f820869ac29a52b47cb8
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.32-0.tgz
    version: 0.0.32-0
  - apiVersion: v2
    appVersion: v0.0.31
    created: "2023-11-18T15:47:26.182807+02:00"
    description: A Helm chart to install Vector Operator
    digest: 45b924c07a825e0f7cd3fb534a6ffd16604790d13be1aff59150c045474754e3
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.31.tgz
    version: 0.0.31
  - apiVersion: v2
    appVersion: v0.0.30
    created: "2023-11-18T15:47:26.181715+02:00"
    description: A Helm chart to install Vector Operator
    digest: 03beda549d15f50325028ea29af5f2065ac0b8adf3078bf7dc1312981aa5e7db
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.30.tgz
    version: 0.0.30
  - apiVersion: v2
    appVersion: v0.0.29
    created: "2023-11-18T15:47:26.181005+02:00"
    description: A Helm chart to install Vector Operator
    digest: 0f025fc3a924b37b8c4131c4d8cfa437d2d4e557ab9476ed3e69a00232c7dca6
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.29.tgz
    version: 0.0.29
  - apiVersion: v2
    appVersion: v0.0.28
    created: "2023-11-18T15:47:26.180327+02:00"
    description: A Helm chart to install Vector Operator
    digest: af856d41314313e04f15e7143409a9c564c6ca610b0d2eaec3112add8573e668
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.28.tgz
    version: 0.0.28
  - apiVersion: v2
    appVersion: v0.0.27
    created: "2023-11-18T15:47:26.179622+02:00"
    description: A Helm chart to install Vector Operator
    digest: 631e2ff02bbd7f247cb486494fd2af60c57cc551066a6a3858226551bc1745a4
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.27.tgz
    version: 0.0.27
  - apiVersion: v2
    appVersion: v0.0.26
    created: "2023-11-18T15:47:26.178409+02:00"
    description: A Helm chart to install Vector Operator
    digest: 760a2833f4c1a33466982419b079ff18d996331ebacc40cf93b0f55229cdb7db
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.26.tgz
    version: 0.0.26
  - apiVersion: v2
    appVersion: v0.0.25
    created: "2023-11-18T15:47:26.177654+02:00"
    description: A Helm chart to install Vector Operator
    digest: fd22b996b071b6d85740ccf76e85cb640fa717c2620748d206d3f4fdd44cbcc2
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.25.tgz
    version: 0.0.25
  - apiVersion: v2
    appVersion: v0.0.24
    created: "2023-11-18T15:47:26.176849+02:00"
    description: A Helm chart to install Vector Operator
    digest: ea257e60ecde063a0d1ed52ce5e3283245b8f0e2daba58ea3a5adb0ba82d7799
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.24.tgz
    version: 0.0.24
  - apiVersion: v2
    appVersion: v0.0.23
    created: "2023-11-18T15:47:26.175635+02:00"
    description: A Helm chart to install Vector Operator
    digest: 546d202b3b9263f789b88335263191098dfcabd5d8698105f37cad24d56a8ed0
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.23.tgz
    version: 0.0.23
  - apiVersion: v2
    appVersion: v0.0.22
    created: "2023-11-18T15:47:26.174801+02:00"
    description: A Helm chart to install Vector Operator
    digest: bf96ddc8ac61e9d6beb8bc763fbf3fa6025d950b29d70d80de6e8a0ea45e0411
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.22.tgz
    version: 0.0.22
  - apiVersion: v2
    appVersion: v0.0.21
    created: "2023-11-18T15:47:26.174077+02:00"
    description: A Helm chart to install Vector Operator
    digest: d37b3064c0374d71e06c0131bcac2bf9e60ec4d62fcbbb20704c5277eabd899d
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.21.tgz
    version: 0.0.21
  - apiVersion: v2
    appVersion: v0.0.20
    created: "2023-11-18T15:47:26.173325+02:00"
    description: A Helm chart to install Vector Operator
    digest: b95cd9ea8b74fde85175411129f77bf7a7afb4e9324ba2d02d489d0d6ef42d6d
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.20.tgz
    version: 0.0.20
  - apiVersion: v2
    appVersion: v0.0.19
    created: "2023-11-18T15:47:26.172393+02:00"
    description: A Helm chart to install Vector Operator
    digest: bc1acd8b21a95e373702daa9c4ce4226b28f56b9c9299482d47b200baddbec14
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.19.tgz
    version: 0.0.19
  - apiVersion: v2
    appVersion: v0.0.18
    created: "2023-11-18T15:47:26.171966+02:00"
    description: A Helm chart to install Vector Operator
    digest: 2bf9cde6eec7b00bfc70d7ac79b1e9d4bf3a406749c6b2bd816f20efd0cb44c3
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.18.tgz
    version: 0.0.18
  - apiVersion: v2
    appVersion: v0.0.17
    created: "2023-11-18T15:47:26.171534+02:00"
    description: A Helm chart to install Vector Operator
    digest: edb51a059b9231f9bc2e2e0dd82c432d0e799a6767a7829ee113054478e098ed
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.17.tgz
    version: 0.0.17
  - apiVersion: v2
    appVersion: v0.0.16
    created: "2023-11-18T15:47:26.171107+02:00"
    description: A Helm chart to install Vector Operator
    digest: 06e33602d72c44cf6779152df4936133ed87e228dd71cbb6615aa4c2666a1ee1
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.16.tgz
    version: 0.0.16
  - apiVersion: v2
    appVersion: v0.0.15
    created: "2023-11-18T15:47:26.170649+02:00"
    description: A Helm chart to install Vector Operator
    digest: 6c9f5ba7a914329caa4f93342d3415fcf4e5fe39f5b7db69173896ea13a47c5b
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.15.tgz
    version: 0.0.15
  - apiVersion: v2
    appVersion: v0.0.14
    created: "2023-11-18T15:47:26.169909+02:00"
    description: A Helm chart to install Vector Operator
    digest: 9f7a3b66247dea7f826b2b38202b0ddfa72b30ecc0954d75be36e066deda9df9
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.14.tgz
    version: 0.0.14
  - apiVersion: v2
    appVersion: v0.0.13
    created: "2023-11-18T15:47:26.169503+02:00"
    description: A Helm chart to install Vector Operator
    digest: c88a1866a20fb2aea4a23886e6e60080eba9ae7ef2706f492d9b329dc9ddf49b
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.13.tgz
    version: 0.0.13
  - apiVersion: v2
    appVersion: v0.0.12
    created: "2023-11-18T15:47:26.169077+02:00"
    description: A Helm chart to install Vector Operator
    digest: 384e8fd8f8f743036eaf1415d893158256a2ad9daddcb17a3d0701a528d9f0df
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.12.tgz
    version: 0.0.12
  - apiVersion: v2
    appVersion: v0.0.11
    created: "2023-11-18T15:47:26.16866+02:00"
    description: A Helm chart to install Vector Operator
    digest: 29e1e04c1706b88ef61ed6c91a45847e6069843419515a33046c5929b179e273
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.11.tgz
    version: 0.0.11
  - apiVersion: v2
    appVersion: v0.0.10
    created: "2023-11-18T15:47:26.168294+02:00"
    description: A Helm chart to install Vector Operator
    digest: f4398224ce88b852b319c950d0f39bfd5e6181801c1fac1b42b069dd2d358078
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.10.tgz
    version: 0.0.10
  - apiVersion: v2
    appVersion: v0.0.9
    created: "2023-11-18T15:47:26.184952+02:00"
    description: A Helm chart to install Vector Operator
    digest: 66c528b6daa9f6fb9a8dd91895b69151f3f0183f4685ba4a2bc026fac27f25a7
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.9.tgz
    version: 0.0.9
  - apiVersion: v2
    appVersion: v0.0.8
    created: "2023-11-18T15:47:26.184608+02:00"
    description: A Helm chart to install Vector Operator
    digest: 21c4c214cd0206abb743e82ac757804d644de08d80eb5f2edbb82ff9668cfed3
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.8.tgz
    version: 0.0.8
  - apiVersion: v2
    appVersion: v0.0.7
    created: "2023-11-18T15:47:26.184259+02:00"
    description: A Helm chart to install Vector Operator
    digest: 27915a2bf70da3f66d08cf4a1f6c41ad38937759ad52eaf8b19f5a3e348e2f2e
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.7.tgz
    version: 0.0.7
  - apiVersion: v2
    appVersion: v0.0.6
    created: "2023-11-18T15:47:26.183908+02:00"
    description: A Helm chart to install Vector Operator
    digest: 26760fbc2018336c12e8726307a624970ee994c4ffa021cc216c13669bd82f09
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: v0.0.5
    created: "2023-11-18T15:47:26.167914+02:00"
    description: A Helm chart to install Vector Operator
    digest: 1d6034027ae2f08a9dbea4d6ee9a1604117ae44d9daceb3f654b87a99175251f
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.1.tgz
    version: 0.0.1
generated: "2023-11-18T15:47:26.167412+02:00"
