---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: vectors.observability.kaasops.io
spec:
  group: observability.kaasops.io
  names:
    kind: Vector
    listKind: VectorList
    plural: vectors
    singular: vector
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Vector is the Schema for the vectors API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VectorSpec defines the desired state of Vector
            properties:
              agent:
                description: Vector Agent
                properties:
                  service:
                    type: boolean
                type: object
              disableAggregation:
                description: DisableAggregation
                type: boolean
            type: object
          status:
            description: VectorStatus defines the observed state of Vector
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
